version: '3.0'
services:
  nginx-php7:
    build: ./.docker
    environment:
      - PHP_XDEBUG=false
      - TZ=America/Sao_Paulo
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes: ['./:/var/www/']
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
